sudo: false
language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction --no-script
  - php bin/console doctrine:database:create --env=test --no-interaction
  - php bin/console doctrine:schema:create --env=test --no-interaction
  - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
  - phpunit