imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        -  'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "5.7"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  "%mailer_user%"
    password: "%mailer_password%"
    spool:     { type: memory }


stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            sluggable: true

fos_user:
    db_driver:    orm
    firewall_name: main
    user_class: AppBundle\Entity\User\User
    from_email:
        address: "admin@warhantmille.fr"
        sender_name: Warhantmille

ivory_ck_editor:
  configs:
    my_config_1:
      toolbar: "my_toolboar_1"
      language: fr
  toolbars:
    configs:
      my_toolboar_1: [["Cut","-","Copy","-","Paste"],"/",["Bold","-","Italic","-","Underline","-","Strike","-","Subscript","-","Superscript"],"-",["Indent","-","JustifyLeft","-","JustifyCenter","-","JustifyRight"],"/",["Image"],"/",["Style","-","Format","-","Font","-","FontSize"],"/",["TextColor","-","BGColor"]]

liip_imagine:
  resolvers:
    default:
      web_path: ~

  filter_sets:
    cache: ~
    thumb:
      quality: 50
      filters:
        thumbnail: { size: [200, 200], mode: outbound }

easy_admin:
  list:
      max_results: 100
  entities:
    Armies:
      class: AppBundle\Entity\Army\Army
      form:
        fields:
          - name
          - points
          - race
          - user
    Equipements:
      class: AppBundle\Entity\Unit\Equipement
      form:
        fields:
          - name
          - points
          - { property: 'units', type_options: { by_reference: false }}
    Units:
      class: AppBundle\Entity\Unit\Unit
      form:
        fields:
          - name
          - points
          - race
          - groupe
          - equipements
          - { property: 'figurines', type_options: { by_reference: false } }
    UnitsArmy:
      class: AppBundle\Entity\Army\UnitArmy
      form:
        fields:
          - points
          - unit
          - army
          - equipements
    Groupes:
      class: AppBundle\Entity\Unit\Groupe
    Races:
      class: AppBundle\Entity\Unit\Race
      form:
          fields:
            - name
    Battles:
      class: AppBundle\Entity\Battle\Battle
    Participants:
      class: AppBundle\Entity\Battle\Participant
    Presences:
      class: AppBundle\Entity\Battle\Presence
    Resumes:
      class: AppBundle\Entity\Battle\Resume
    Figurine:
      class: AppBundle\Entity\Unit\Figurine
    Type:
      class: AppBundle\Entity\Unit\Type