# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha1

    role_hierarchy:
      ROLE_ADMIN:   ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_USER
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true

        main_reset:
            pattern: ^/resetting
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:  true
            anonymous: false
            remember_me:
                secret: "%secret%"


    access_control:
    - { path: ^/login$, role:  IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role:  IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role:  IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, roles: ROLE_SUPER_ADMIN }
    - { path: ^/battle/delete/, roles: ROLE_SUPER_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
