<?php

namespace AppBundle\Repository\Army;

/**
 * ArmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneWithAll($slugArmy)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->leftJoin('a.figurines', 'f')
			->addSelect('f')
			->leftJoin('f.figurine', 'fi')
			->addSelect('f')
			->leftJoin('f.equipements', 'e')
			->addSelect('e')
			->leftJoin('f.photos', 'ph')
			->addSelect('ph')
			->where('a.slugArmy = :slugArmy')
			->setParameter('slugArmy', $slugArmy);

		return $qb->getQuery()->getOneOrNullResult();
	}
}
