<?php

namespace AppBundle\Repository\Army;

/**
 * ArmyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneWithAll($slug)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->leftJoin('a.units', 'u')
            ->addSelect('u')
            ->leftJoin('u.unit', 'un')
            ->addSelect('u')
            ->leftJoin('u.equipements', 'e')
            ->addSelect('e')
            ->leftJoin('u.photos', 'ph')
            ->addSelect('ph')
            ->where('a.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findArmiesOfUser($user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.user = :user')
            ->setParameter('user', $user);

        return $qb;
    }
}
