<?php

namespace AppBundle\Repository\Army;

/**
 * EquipementFigurineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementFigurineRepository extends \Doctrine\ORM\EntityRepository
{
}
