<?php

namespace AppBundle\Repository\Army;

/**
 * OptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByRace($race)
	{
		$qb = $this->createQueryBuilder('e');

		$qb->innerJoin('e.figurines','eq')
			->addSelect('eq')
			->innerJoin('eq.figurine','f')
			->addSelect('f')
			->where('f.race = :race')
			->setParameter('race', $race);

		return $qb;
	}public function findByFigurine($figurine)
	{
		$qb = $this->createQueryBuilder('e');

		$qb->innerJoin('e.figurines','eq')
			->addSelect('eq')
			->where('eq.figurine = :figurine')
			->setParameter('figurine', $figurine);

		return $qb;
	}
}
