<?php

namespace AppBundle\Repository\Army;

/**
 * EquipementFigurineArmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementFigurineArmyRepository extends \Doctrine\ORM\EntityRepository
{
}
