<?php

namespace AppBundle\Repository\Army;

/**
 * FigurineArmyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurineArmyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroup($group, $army)
    {
        $qb = $this->createQueryBuilder('f');

        $qb->leftJoin('f.army', 'a')
            ->leftJoin('f.figurine', 'fi')
            ->addSelect('fi')
            ->leftJoin('fi.groupe','g')
            ->leftJoin('f.photos', 'ph')
            ->addSelect('ph')
            ->where('a.id = :army')
            ->andWhere('g.id= :group')
            ->setParameters(array('army' => $army,'group' => $group))
            ->orderBy('fi.name','ASC')
            ;

        return $qb->getQuery()->getResult();
    }
}
