<?php

namespace AppBundle\Repository\Army;

/**
 * FigurineArmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurineArmyRepository extends \Doctrine\ORM\EntityRepository
{
}
