<?php

namespace AppBundle\Repository\Army;

/**
 * PhotoFigurineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoFigurineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForFigurine($figurine)
    {
        $qb = $this->createQueryBuilder('ph');

        $qb->where('ph.figurine = :figurine')
            ->setParameter('figurine', $figurine);
        return $qb;
    }
}
