<?php

namespace AppBundle\Repository\Army;

/**
 * UnitArmyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitArmyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroup($group, $army)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->leftJoin('u.army', 'a')
            ->leftJoin('u.figurine', 'un')
            ->addSelect('un')
            ->leftJoin('un.groupe','g')
            ->leftJoin('u.photos', 'ph')
            ->addSelect('ph')
            ->where('a.id = :army')
            ->andWhere('g.id= :group')
            ->setParameters(array('army' => $army,'group' => $group))
            ->orderBy('un.name','ASC')
            ;

        return $qb->getQuery()->getResult();
    }
}
