army_list:
    path: /list
    defaults:
        _controller: "AppBundle:Army:list"


army_create:
    path: /create
    defaults:
        _controller: "AppBundle:Army:create"

army_edit:
    path: /{slug}/edit
    defaults:
        _controller: "AppBundle:Army:edit"

army_delete:
    path: /{slug}/delete
    defaults:
        _controller: "AppBundle:Army:delete"

army_view:
    path: /{slug}
    defaults:
        _controller: "AppBundle:Army:view"
