battle_list:
    path: /list
    defaults:
        _controller: "AppBundle:Battle:list"
    methods: [ GET ]

battle_create:
    path: /create
    defaults:
        _controller: "AppBundle:Battle:create"
    methods: [ GET, POST ]

battle_view:
    path: /{slug}
    defaults:
        _controller: "AppBundle:Battle:view"
    methods: [ GET, POST ]

battle_edit:
    path: /{slug}/edit
    defaults:
        _controller: "AppBundle:Battle:edit"
    methods: [ GET, POST ]

battle_canceled:
    path:  /{slug}/canceled
    defaults:
        _controller: "AppBundle:Battle:canceled"
    methods: [ GET, POST ]

battle_delete:
    path:  /{slug}/delete
    defaults:
        _controller: "AppBundle:Battle:delete"
    methods: [ GET ]
