battle_list:
    path: /list
    defaults:
        _controller: "AppBundle:Battle:list"

battle_future_view:
    path: /future/{slugBattle}
    defaults:
        _controller: "AppBundle:Battle:viewFuture"

battle_create:
    path: /create
    defaults:
        _controller: "AppBundle:Battle:create"

battle_view:
    path: /{slugBattle}
    defaults:
        _controller: "AppBundle:Battle:view"

battle_edit:
    path: /{slugBattle}/edit
    defaults:
        _controller: "AppBundle:Battle:edit"

battle_canceled:
    path:  /{slugBattle}/canceled
    defaults:
        _controller: "AppBundle:Battle:canceled"

battle_delete:
    path:  /{slugBattle}/delete
    defaults:
        _controller: "AppBundle:Battle:delete"
