figurine_army_create:
    path: /{slug}/create
    defaults:
       _controller: "AppBundle:FigurineArmy:create"

figurine_army_edit:
    path: /{id}/edit
    defaults:
        _controller: "AppBundle:FigurineArmy:edit"
    requirements:
      id: \d+

figurine_army_delete:
    path: /{id}/delete
    defaults:
        _controller: "AppBundle:FigurineArmy:delete"
    requirements:
      id: \d+
