photo_figurine_add:
    path: /{id}/add
    defaults:
        _controller: "AppBundle:PhotoFigurine:add"
    requirements:
        id: \d+

figurine_photo_delete:
    path:  /{id}/delete
    defaults:
        _controller: "AppBundle:PhotoFigurine:delete"
    requirements:
        id: \d+