resume_create:
    path: /{slug}/create
    defaults:
        _controller: "AppBundle:Resume:create"

resume_edit:
    path: /{id}/edit
    defaults:
        _controller: "AppBundle:Resume:edit"
    requirements:
      id: \d+
