unit_army_create:
    path: /{slug}/create
    defaults:
       _controller: AppBundle:UnitArmy:selectUnit
    methods: [ GET, POST]

unit_army_adding_figurines:
    path: /{slug}/{id}/adding-figurines
    defaults:
        _controller: AppBundle:UnitArmy:addingFigurines
    methods: [ GET, POST]

unit_army_edit:
    path: /{id}/edit
    defaults:
        _controller: AppBundle:UnitArmy:edit
    methods: [ GET, POST]

unit_army_delete:
    path: /{id}/delete
    defaults:
        _controller: AppBundle:UnitArmy:delete
    methods: [ GET, POST]
