unit_army_create:
    path: /{slug}/create
    defaults:
       _controller: "AppBundle:UnitArmy:create"

unit_army_edit:
    path: /{id}/edit
    defaults:
        _controller: "AppBundle:UnitArmy:edit"
    requirements:
      id: \d+

unit_army_delete:
    path: /{id}/delete
    defaults:
        _controller: "AppBundle:UnitArmy:delete"
    requirements:
      id: \d+
