user:
    path: /view
    defaults:
        _controller: "AppBundle:User:view"

user_edit:
    path: /{id}/edit
    defaults:
        _controller: "AppBundle:User:edit"
    requirements:
      id: \d+

user_role:
    path:  /{id}
    defaults:
        _controller: "AppBundle:User:addRole"
    requirements:
      id: \d+