app_home:
    path: /
    defaults: { _controller: "AppBundle:App:index"}

app_battle:
    resource: 'routing/battle.yml'
    prefix: /battle

app_army:
    resource: 'routing/army.yml'
    prefix: /army

app_figurine_army:
    resource: 'routing/figurine.army.yml'
    prefix: /figurine

app_photo_user:
    resource: 'routing/photo.user.yml'
    prefix: /photo/user

app_resume:
    resource: 'routing/resume.yml'
    prefix: /resume

app_user:
    resource: 'routing/user.yml'
    prefix: /user

app_race:
    resource: 'routing/race.yml'
    prefix: /race