services:
   battle.send_mail:
       class: AppBundle\Mail\SendMail
       arguments: ['@mailer', '@twig']

   battle.add_participants:
       class: AppBundle\Battle\ParticipantsBattle
       arguments: ['@doctrine.orm.entity_manager']

#   participant.form:
#       class: AppBundle\Form\Type\Battle\CombattantType
#       arguments: ['@doctrine.orm.entity_manager']

