<?php

namespace AppBundle\Repository\Unit;

/**
 * EquipementFigurineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipementUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
