admin_unit_create:
    path: /create
    defaults:
      _controller: AppBundle:Administration/Unit:create
    methods: [ GET, POST ]

admin_unit_edit:
    path: /{id}/edit
    defaults:
      _controller: AppBundle:Administration/Unit:edit
    methods: [ GET, POST ]

admin_unit_delete:
    path: /{id}/delete
    defaults:
      _controller: AppBundle:Administration/Unit:delete
    methods: [ GET ]

admin_unit_index:
    path: /index
    defaults:
      _controller: AppBundle:Administration/Unit:index
    methods: [ GET ]

admin_unit_filter:
    path: /filter
    defaults:
      _controller:  AppBundle:Administration/Unit:filter
    methods: [ GET ]
