<?php

namespace AppBundle\Repository\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrder()
  {
    $qb = $this->createQueryBuilder('u');

    $qb->orderBy('u.username');

    return $qb->getQuery()->getResult();
  }

  public function findAllForm()
  {
    $qb = $this->createQueryBuilder('u');
    $qb->orderBy('u.username');

    return $qb;
  }
}
