<?php

namespace AppBundle\Repository\Battle;

/**
 * LegendPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegendPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
