<?php

namespace AppBundle\Repository\Battle;

/**
 * PhotoBattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoBattleRepository extends \Doctrine\ORM\EntityRepository
{
}
