<?php

namespace AppBundle\Repository\Battle;

/**
 * PhotoBattleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoBattleRepository extends \Doctrine\ORM\EntityRepository
{
    // Requete affichant les photos battle d'un visiteur par date et id descendant
    public function findByDesc($user){
        $qb = $this->createQueryBuilder('ph');

        $qb->where('ph.user = :user')
            ->setParameter(':user', $user)
            ->addOrderBy('ph.date_upload', 'DESC')
            ->addOrderBy('ph.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
